<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE socios [
   <!ELEMENT socios (socio)*>
   <!ELEMENT socio ((numero, clave)+, nombre, edad)>
   <!ELEMENT clave (#PCDATA)>
   <!ELEMENT edad (#PCDATA)>
   <!ELEMENT nombre (#PCDATA)>
   <!ELEMENT numero (#PCDATA)>
]>
<!-- SoluciÃ³n Ejercicio 3 -->
<socios>
   <socio>
        <numero>598</numero>
        <clave>hY75Du</clave>
        <nombre>Ana</nombre>
        <edad>21</edad>
   </socio>
   <socio>
        <numero>599</numero>
        <clave>hY75Da</clave>
        <nombre>Iker</nombre>
        <edad>19</edad>
   </socio>
   <socio>
        <numero>600</numero>
        <clave>hY75Db</clave>
        <nombre>Ana</nombre>
        <edad>19</edad>
   </socio>
</socios>