=== hunkstalker/Entregas-HTML-CSS-XML-DAM1_20-21/archivo-dtd/comanda.dtd
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE comanda [
<!ELEMENT comanda (client, articles, total)>
<!ELEMENT client (nom, cognom)>
<!ELEMENT nom (#PCDATA)>
<!ELEMENT cognom (#PCDATA)>
<!ELEMENT articles (article+)>
<!ELEMENT article (descripcio, quantitat, preu)>
<!ELEMENT descripcio (#PCDATA)>
<!ELEMENT quantitat (#PCDATA)>
<!ELEMENT preu (#PCDATA)>
<!ELEMENT total (#PCDATA)>

<!ATTLIST comanda numero CDATA #REQUIRED>
<!ATTLIST comanda dia CDATA #REQUIRED>
<!ATTLIST client codi ID #REQUIRED>
<!ATTLIST total valor CDATA "0">
]>
<!-- 
<comanda numero="26" dia="2020-11-01">
	<client codi="20">
		<nom>Billy</nom>
		<cognom>Elliott</cognom>
	</client>
	<articles>
		<article>
			<descripci贸>Sabates de ballarina</descripci贸>
			<quantitat>2</quantitat>
			<preu>99,95</preu>
		</article>
		<article>
			<descripci贸>Funda per Iphone</descripci贸>
			<quantitat>1</quantitat>
			<preu>19,95</preu>
		</article>
	</articles>
	<total valor="219,85" />
</comanda>
-->

=== hunkstalker/Entregas-HTML-CSS-XML-DAM1_20-21/archivo-dtd/Exercici XML-DTD.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE comanda SYSTEM "./comanda.dtd">
<comanda numero="26" dia="2020-11-01">
	<client codi="20">
		<nom>Billy</nom>
		<cognom>Elliott</cognom>
	</client>
	<articles>
		<article>
			<descripci贸>Sabates de ballarina</descripci贸>
			<quantitat>2</quantitat>
			<preu>99,95</preu>
		</article>
		<article>
			<descripci贸>Funda per Iphone</descripci贸>
			<quantitat>1</quantitat>
			<preu>19,95</preu>
		</article>
	</articles>
	<total valor="219,85" />
</comanda>
